# Generated by Django 4.2.4 on 2023-08-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='Photo')),
                ('desc', models.TextField()),
                ('year', models.DateTimeField()),
            ],
        ),
    ]
