# Generated by Django 4.2.4 on 2023-09-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moviesapp', '0002_alter_movies_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(),
        ),
    ]
